name: ui-roisummary
rundeckPluginVersion: 1.3
author: Eric Chapman | Rundeck Team
url: https://github.com/rundeck-plugins/ui-roi-summary
date: 2024-01-20T19:50:16.097Z
version: 1.0.0
providers:
    - name: ui-roisummary
      service: UI
      plugin-type: ui
      title: "ROI Summary"
      description: "ROI Summary Views on Job List and Job Activities pages."
      ui:
        - pages: ['menu/jobs', 'scheduledExecution/show']
          scripts:
            - js/chart.min.js
            - js/init.js
            - js/joblist.js
          styles:
            - css/styles.css