name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Get Fetch Tags
        run: git fetch --tags --force
        if: "!startsWith(github.ref, 'refs/tags')"
        
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          
      - name: Cache Gradle and Assets
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            .gradle
            build/assets
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle', '**/gradle-wrapper.properties', 'src/main/rdplugin/assets/**') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
            
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build Plugin
        run: |
          ./gradlew clean assetCompile build --info
        env:
          GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2"
          
      - name: Get Release Version
        id: get_version
        run: |
          # Redirect version output to a file to avoid printing to stdout
          ./gradlew currentVersion -q -Prelease.quiet > version.txt
          VERSION=$(cat version.txt)
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
          echo "Detected version: ${VERSION}"
          
      - name: Show build contents
        run: |
          echo "Build directory contents:"
          find build/ -ls
          
      - name: Upload Plugin Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ui-roisummary-${{ steps.get_version.outputs.VERSION }}
          path: |
            build/distributions/ui-roisummary-${{ steps.get_version.outputs.VERSION }}.zip
          if-no-files-found: error